// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CompanyEmployees.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230613194809_InitialData-SeedData-2")]
    partial class InitialDataSeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "583 Wall Dr. Gwynn Oak, MD 21207",
                            Country = "USA",
                            Name = "IT Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Address = "312 Forest Avenue, BF 923",
                            Country = "USA",
                            Name = "Admin Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("f91d276d-2488-4e68-bf2f-85996f029daf"),
                            Address = "987 Maple Drive, Los Angeles, CA 90210",
                            Country = "USA",
                            Name = "Vector Digital Corp"
                        },
                        new
                        {
                            Id = new Guid("7e9f0f5c-58ef-4a77-913f-3e408054e1bb"),
                            Address = "45 Ocean Street, Sydney, NSW 2000",
                            Country = "Australia",
                            Name = "Oceanic Software Ltd"
                        },
                        new
                        {
                            Id = new Guid("eb23df43-47b3-4675-9b84-2788574e2e95"),
                            Address = "Suite 1, 1 Baker Street, London, W1U 6WG",
                            Country = "UK",
                            Name = "CloudNet Technologies"
                        },
                        new
                        {
                            Id = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Address = "6782 Pine St. Toronto, ON M4B 1V6",
                            Country = "Canada",
                            Name = "Polaris Software"
                        },
                        new
                        {
                            Id = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Address = "742 Evergreen Terrace, Springfield, IL 62701",
                            Country = "USA",
                            Name = "Stratosphere Technologies"
                        },
                        new
                        {
                            Id = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Address = "Rua da Consolação, 2222, São Paulo - SP, 01302-000",
                            Country = "Brazil",
                            Name = "Nimbus Innovations"
                        },
                        new
                        {
                            Id = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Address = "210 Great Portland Street, London, W1W 5AF",
                            Country = "UK",
                            Name = "Equinox Digital"
                        },
                        new
                        {
                            Id = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Address = "2-11-3 Meguro, Meguro-ku, Tokyo 153-0063",
                            Country = "Japan",
                            Name = "Helix AI"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Sam Raiden",
                            Position = "Software developer"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Jana McLeaf",
                            Position = "Software developer"
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Age = 35,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Kane Miller",
                            Position = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("aee7b7f5-345c-4a46-8aec-0c6c9a6f9b1b"),
                            Age = 32,
                            CompanyId = new Guid("f91d276d-2488-4e68-bf2f-85996f029daf"),
                            Name = "Adam Scott",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("a5a65b91-b3e6-4f78-a40c-6b72a5a1f827"),
                            Age = 29,
                            CompanyId = new Guid("7e9f0f5c-58ef-4a77-913f-3e408054e1bb"),
                            Name = "Emily Parker",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("3c4cd4f9-913f-41e1-a9dd-5c8f8b2b6c2a"),
                            Age = 35,
                            CompanyId = new Guid("eb23df43-47b3-4675-9b84-2788574e2e95"),
                            Name = "Oliver Brown",
                            Position = "System Analyst"
                        },
                        new
                        {
                            Id = new Guid("cb4b5c89-35f1-4bb6-b810-66a6f2c6b2db"),
                            Age = 27,
                            CompanyId = new Guid("f91d276d-2488-4e68-bf2f-85996f029daf"),
                            Name = "Sophia Davis",
                            Position = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("f0e2058c-8745-4a3a-9fdc-058a4f55a802"),
                            Age = 33,
                            CompanyId = new Guid("7e9f0f5c-58ef-4a77-913f-3e408054e1bb"),
                            Name = "Liam Smith",
                            Position = "IT Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("5a98cd2d-bb8d-4021-8b21-d45551d3c288"),
                            Age = 32,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Jake Mitchell",
                            Position = "Web Developer"
                        },
                        new
                        {
                            Id = new Guid("fbdf89c3-66af-455b-9b26-3b1c8b2a3f9d"),
                            Age = 29,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Jessica Walters",
                            Position = "System Analyst"
                        },
                        new
                        {
                            Id = new Guid("3edc9737-b355-4a6a-9ecf-c8eac566c1b8"),
                            Age = 35,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Lucas Alves",
                            Position = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("e2dcedf3-51b8-4a7b-853b-9d2954e2ef32"),
                            Age = 27,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Olivia Baker",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("891bb83c-b2f6-4c88-830a-1b7681f50fe0"),
                            Age = 33,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Haruto Yamada",
                            Position = "IT Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("b3fa5067-e7c5-4618-9f34-3a8a6e8827ed"),
                            Age = 32,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Liam Johnson",
                            Position = "Web Developer"
                        },
                        new
                        {
                            Id = new Guid("64a183c9-93d7-4372-bef8-a2f40f7e520d"),
                            Age = 29,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Noah Williams",
                            Position = "System Analyst"
                        },
                        new
                        {
                            Id = new Guid("fb133c53-33a6-4f94-9623-4896fd4527cf"),
                            Age = 35,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Oliver Brown",
                            Position = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("5b34df28-fdc8-4a2b-a9a6-1f8b06248831"),
                            Age = 27,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Elijah Davis",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("6e6d4c1f-b025-47c2-9e73-e84e5c42bc21"),
                            Age = 33,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "James Wilson",
                            Position = "IT Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("42d5b53a-9dba-46ef-8127-72c5ec75cb4a"),
                            Age = 34,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "William Thomas",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("f8c9f6fa-61ba-45f6-9107-0a3d688ba2d9"),
                            Age = 28,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Benjamin Martinez",
                            Position = "Network Administrator"
                        },
                        new
                        {
                            Id = new Guid("23b5e303-96d6-4ba2-8d52-2e2a8c30ab67"),
                            Age = 36,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Lucas Garcia",
                            Position = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("7dc92c9f-6ad1-4117-9677-27a45f1a9a35"),
                            Age = 30,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Henry Rodriguez",
                            Position = "Systems Engineer"
                        },
                        new
                        {
                            Id = new Guid("9db9db79-3434-4db6-925d-bb3ed6e6b213"),
                            Age = 32,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Alexander Martinez",
                            Position = "IT Coordinator"
                        },
                        new
                        {
                            Id = new Guid("0d3a45e6-876b-4ca3-92eb-4167eb7ef621"),
                            Age = 34,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Evelyn Clarke",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("e8a79a80-23cd-42d1-88b2-c8e68e484a43"),
                            Age = 28,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Charlie White",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("abf0ed9e-c23a-4a8e-97ea-d1486d837972"),
                            Age = 36,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Freddie Harris",
                            Position = "Product Manager"
                        },
                        new
                        {
                            Id = new Guid("265f40c3-0cb7-4a3d-9169-32b110dbb557"),
                            Age = 30,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "George Lewis",
                            Position = "Data Engineer"
                        },
                        new
                        {
                            Id = new Guid("9d7e8df3-55d9-4596-987c-6a3d0469aae3"),
                            Age = 32,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Isla Walker",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("3785fa0b-8106-4c53-9053-ef9b2a3a9308"),
                            Age = 27,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Leo Hall",
                            Position = "Web Designer"
                        },
                        new
                        {
                            Id = new Guid("b3d702fc-a551-40b2-b333-7ae0979c8b5e"),
                            Age = 37,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Jacob Turner",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("f5eaeb2f-b2f2-4fdb-9358-a6e582f27f2c"),
                            Age = 26,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Mason Phillips",
                            Position = "Quality Assurance"
                        },
                        new
                        {
                            Id = new Guid("d859f253-8eb0-43be-9480-911210b6ca00"),
                            Age = 34,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Harrison Campbell",
                            Position = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("1e7f9e6c-3fab-4d37-8b48-6922a60e799a"),
                            Age = 29,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Jessica Scott",
                            Position = "Cloud Architect"
                        },
                        new
                        {
                            Id = new Guid("cd145578-9e91-4d08-9a00-4b3cbe9c5c47"),
                            Age = 28,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Matilda Young",
                            Position = "Scrum Master"
                        },
                        new
                        {
                            Id = new Guid("bb8a2f24-8b36-44b7-bca4-c593aadd5f9e"),
                            Age = 37,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Oscar King",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("8233b39a-2c0b-4cf2-8bca-48f3728eb6a3"),
                            Age = 26,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Sophia Wright",
                            Position = "Network Engineer"
                        },
                        new
                        {
                            Id = new Guid("756b50c1-853f-4c07-b495-304f7164118a"),
                            Age = 35,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Theo Taylor",
                            Position = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("234fd123-89a2-4a47-a4c9-5b7e4f7e59e6"),
                            Age = 32,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Zachary Martin",
                            Position = "IT Manager"
                        },
                        new
                        {
                            Id = new Guid("abd7b2f7-8cb8-40c3-a6d6-ae6196cde283"),
                            Age = 31,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Owen Baker",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("9f47d9c4-70eb-4662-a3cd-ec5fa1c602a7"),
                            Age = 27,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Emily Clarke",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("5b5ffbef-e367-4294-b847-3e3b7a8e84e8"),
                            Age = 35,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Ian Freeman",
                            Position = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("12fa66df-1dd2-4112-93cd-c31014a0b777"),
                            Age = 28,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Amelia Davis",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("93547f13-d909-4ca9-9696-22dcbc9b0ee9"),
                            Age = 31,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Noah Patterson",
                            Position = "IT Consultant"
                        },
                        new
                        {
                            Id = new Guid("87cb4988-a5d2-4b36-b5d3-71184f6e3f75"),
                            Age = 26,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Liam Johnson",
                            Position = "Network Administrator"
                        },
                        new
                        {
                            Id = new Guid("0baee42d-cb8f-4d67-8a82-c91335d479b8"),
                            Age = 30,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Oliver Smith",
                            Position = "Web Developer"
                        },
                        new
                        {
                            Id = new Guid("ad24c897-1cde-4b0b-828d-b15c4a07a24d"),
                            Age = 28,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "George Johnson",
                            Position = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("20b3f781-88e0-42c5-b678-e8b3a625f22d"),
                            Age = 26,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Harry Williams",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("c72e7e23-2761-42cf-8962-896ada4425c1"),
                            Age = 32,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Jack Jones",
                            Position = "Systems Administrator"
                        },
                        new
                        {
                            Id = new Guid("ce14b1d1-8133-4279-a407-6bda3a3a8b92"),
                            Age = 25,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Charlie Brown",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("e09b94d2-d5dd-4f80-90d7-35353c49a07f"),
                            Age = 34,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Thomas Davies",
                            Position = "QA Engineer"
                        },
                        new
                        {
                            Id = new Guid("66f9f41a-0d7f-4df3-9b9a-c7533b57c742"),
                            Age = 33,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "Ethan Evans",
                            Position = "Network Engineer"
                        },
                        new
                        {
                            Id = new Guid("8bc3a24d-7337-4c55-b8c9-c9b96b9c8a8e"),
                            Age = 28,
                            CompanyId = new Guid("7304a687-8970-4a37-b3e7-0bf74a5b6456"),
                            Name = "James Wilson",
                            Position = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("c951255a-0e8c-4f6a-9836-8dd3a8d0c3d7"),
                            Age = 31,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "William Taylor",
                            Position = "Software Tester"
                        },
                        new
                        {
                            Id = new Guid("0d6a92bf-8c8c-4a6e-8b56-86e8742d2479"),
                            Age = 29,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Jacob Thomas",
                            Position = "IT Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("10d5c76c-4754-41f6-9220-9326a4e1a583"),
                            Age = 41,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Andrea Bocelli",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("8a34cfdd-8c59-4303-9a81-4fdbe7ecb26b"),
                            Age = 29,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Ella Fitzgerald",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("56fa03f4-49fb-44ba-b045-9bc13c8c5821"),
                            Age = 33,
                            CompanyId = new Guid("d69a6a59-a7e8-4c8f-b802-95d2b4b58ac7"),
                            Name = "Charlie Parker",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("bc8903a5-cb9e-4b28-a5aa-3c7598289f66"),
                            Age = 36,
                            CompanyId = new Guid("ba56711f-692a-4ed6-9451-b3f229f9f468"),
                            Name = "Dizzy Gillespie",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("85daff91-dffa-47f1-922d-b8c994733fb3"),
                            Age = 27,
                            CompanyId = new Guid("f9a92769-354f-4d23-85b2-16f6af0b84a1"),
                            Name = "Sarah Vaughan",
                            Position = "QA Engineer"
                        },
                        new
                        {
                            Id = new Guid("061e682f-5987-41a1-97c5-0a8b6f83e673"),
                            Age = 30,
                            CompanyId = new Guid("e1bce704-7cbb-4b10-beda-d97e9aef9147"),
                            Name = "Frank Sinatra",
                            Position = "IT Consultant"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
